#!/bin/env bash

case "$1" in
"Ip")
  latexmk -pdf -shell-escape -pvc I-existence.tex
  latexmk -c ;;
"I")
  latexmk -pdf -shell-escape I-existence.tex
  latexmk -c ;;
"a")
  cd appmeta
  latexmk -pdf -shell-escape appmeta.tex
  latexmk -c
  cd .. ;;
"clobber")
  find . -regex ".*[Cc]onfli.+." \
    -not -name ".tex" \
    -exec mv -v {} ~/.local/share/Trash/ \;
  latexmk -C
  cd appmeta
  latexmk -C
  cd .. ;;
"git")
  git add -A
  git commit -m "automated update"
  git push ;;
esac
