#!/bin/env bash

case "$1" in
"I")
latexmk -pdf -shell-escape -pvc I-identity.tex
latexmk -c ;;
"II")
latexmk -pdf -shell-escape -pvc II-spheres.tex
latexmk -c ;;
"III")
latexmk -pdf -shell-escape -pvc III-homot.tex
latexmk -c ;;
"III")
latexmk -pdf -shell-escape -pvc IV-mereo.tex
latexmk -c ;;
"all")
latexmk -pdf I-identity
latexmk -pdf II-spheres
latexmk -pdf III-homot
latexmk -pdf IV-mereo
latexmk -c ;;
"d")
latexmk -pdf notes_denta.tex
esac
