#!/bin/env bash

case "$1" in
"I")
latexmk -pdf -shell-escape -pvc I-identity.tex
latexmk -c ;;
"II")
latexmk -pdf -shell-escape -pvc II-spheres.tex
latexmk -c ;;
"III")
latexmk -pdf -shell-escape -pvc III-homot.tex
latexmk -c ;;
"IV")
latexmk -pdf -shell-escape -pvc IV-mereo.tex
latexmk -c ;;
"all")
latexmk -pdf -shell-escape I-identity
latexmk -pdf -shell-escape II-spheres
latexmk -pdf -shell-escape III-homot
latexmk -pdf -shell-escape IV-mereo
latexmk -c ;;
"d")
latexmk -pdf notes_denta.tex ;;
"app")
cd appmeta/
latexmk -pdf appmeta.tex 
cd ..;;
"git")
git add -A 
git commit -m "automated update"
git push ;;
esac
