#!/bin/env bash

case "$1" in
"Ip")
  latexmk -pdf -shell-escape -pvc I-identity.tex
  latexmk -c ;;
"I")
  latexmk -pdf -shell-escape I-identity.tex
  latexmk -c ;;
"a")
  cd appmeta
  latexmk -pdf -shell-escape appmeta.tex
  latexmk -c
  cd .. ;;
"clobber")
  git add -A
  git commit -m "safety update"
  git push
# ^ do a push for safety reason: one never knows what rm deletes...
  find . -regex ".*[Cc]onfli.+." -not -name ".tex" -exec mv -v {} ~/.local/share/Trash/ \;
  latexmk -C
  cd appmeta
  latexmk -C
  cd .. ;;
"git")
  git add -A
  git commit -m "automated update"
  git push ;;
esac
