tex:
	latexmk -pdf -shell-escape fun-erkennen.tex

view:
	evince fun-erkennen.pdf &

clean:
	latexmk -C

git:
	bash -c 'git add -A'
	bash -c 'git commit -m "standard commit perché denta non sa usare bash"'
	bash -c 'git push'
